name: PrettierLint

on: [push, pull_request]

jobs:
  PrettierLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Cache Dependencies
        uses: actions/cache@v2.1.6
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: yarn --immutable
      - name: Prettify and Lint code
        run: yarn prettiest
      - name: Check for Changed Files
        uses: brettcannon/check-for-changed-files@v1.1.0
        with:
          file-pattern: "src/*.ts"
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}

          git add ./src/
          git commit . -m "style: apply ESLint and Prettier"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
