name: Prettier

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Cache Dependencies
        uses: actions/cache@v2.1.6
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: yarn --immutable
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          commit_message: 'style: apply prettier'
          prettier_options: --write src/
          only_changed: True
        env:
          GITHUB_TOKEN: ${{ github.token }}
